name: Receive PR

# read-only repo token
# no access to secrets
on:
  - pull_request_target
      
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          whoami
          ls -lah /home/runner/work/_actions/actions/upload-artifact/v4/dist/upload/index.js

      - run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/justin0989/test3/contents/README \
          -d '{"branch":"main","message":"my commit message","committer":{"name":"Monalisa Octocat","email":"octocat@github.com"},"content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: /tmp/GOOGLEflag
          retention-days: 1
